name:                distributed
version:             0.1.0.0
github:              parsonsmatt/distributed
license:             BSD3
author:              Matt Parsons
maintainer:          parsonsmatt@gmail.com
copyright:           2017 Matt Parsons
synopsis:            Playing with Cloud Haskell
category:            Web
description:         Please see the README on Github at <https://github.com/parsonsmatt/distributed#readme>

extra-source-files:
- README.md

ghc-options:
- -Wall
- -fwarn-incomplete-uni-patterns
- -fwarn-incomplete-record-updates

dependencies:
- base >= 4.7 && < 5
- distributed-process
- network-transport-tcp
- optparse-applicative
- bytestring
- mwc-random
- vector

library:
  source-dirs: src

executables:
  distributed-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - distributed

tests:
  distributed-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - distributed
    - hspec
